### PR TITLE
Map implementaion

### PR DESCRIPTION
**Pull request by eman1408**
Created geocode gem to Gemfile 
Created Mapbox controller
Edited Equipment_listings controller #show to get coordinates 
Added Functional map to show pages 
Created custom map pin
Added basic style 
Screen Shot 2022-07-29 at 1 24 02

### CODE REVIEW

**Review by paylavargas — COMMENTED** [review]
I like the pin. It looks nice. 😎

**Review by paylavargas — COMMENTED** [review]
I was wondering if we also need a map on the index page. When a user enters their desired location, they will see a bunch of listings available in the area.

**Comment by eman1408** [comment]
It wouldn’t be to hard to implement as the framework is basically already set up. But maybe it’s too much for right now?

**Comment by paylavargas** [comment]
> It wouldn’t be to hard to implement as the framework is basically already set up. But maybe it’s too much for right now?

You're right. We can just render it on pages we need it. 💂🏾‍♂️

**Comment by eman1408** [comment]
Yeah just change the controller to take a array of coordinates instead of the single one 🕺

**Pull request merged**
