### PR TITLE
added a basic booking form, updated models and validations, and new and create actions in the bookings_contoller

### PR DESCRIPTION
**Pull request by paylavargas**
- add a basic booking form in the new page, which I might just turn into a partial later

- updated the Booking Model andEquipmentListing Model (removed the unnecessary columns)

- create action is not working, looks like the booking isn't saving, it goes directly to the last line of code which is render :new

### CODE REVIEW

**Comment by TheDemonGuard** [comment]
Is it possible to pull, I fixed some error.

the reason booking is not saving is because of below error.
but I am still trying to figure out why it is blank.

`
@booking.errors.messages
=> {:user=>["must exist"], :book_from=>["can't be blank"], :book_to=>["can't be blank"]}
`

the params contain values for book_form and book_to.
`
booking_params
=> #<ActionController::Parameters {"book_from"=>"2022-07-12", "book_to"=>"2022-07-25"} permitted: true>
`

**Comment by TheDemonGuard** [comment]
The reason was we have "book_from" and "book_to" as time in schema.
but our form is passing date :D  (If i temporary change to date type to date in the schema it works)
(And we have to have a logged in user, otherwise the current_user is nil)

image

**Comment by paylavargas** [comment]
> That's weird. In my schema. The two attributes are both date. Does the schema in your local master look like this?

image

**Comment by paylavargas** [comment]
> Is it possible to pull, I fixed some error.
> 
> the reason booking is not saving is because of below error. but I am still trying to figure out why it is blank.
> 
> `@booking.errors.messages => {:user=>["must exist"], :book_from=>["can't be blank"], :book_to=>["can't be blank"]}`
> 
> the params contain values for book_form and book_to. `booking_params => #<ActionController::Parameters {"book_from"=>"2022-07-12", "book_to"=>"2022-07-25"} permitted: true>`

Thank you for fixing the errors, Henry.

**Pull request merged**
